apiVersion: apps/v1
kind: Deployment

metadata:
  name: db-deploy
  namespace: myspace
  labels:
    name: db-deploy

spec:
  # number of instances
  replicas: 1
  selector:
    matchLabels:
      name: mydb-pod

  # the pod to deploy
  template:
    metadata:
      name: mydb-pod
      namespace: myspace
      labels:
        name: mydb-pod
    spec:
      containers:
        - name: mydb-container
          image: stackupiss/northwind-db:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mydb-service
  namespace: myspace
  labels:
    name: mydb-service
spec:
  type: ClusterIP
  selector:
    name: mydb-pod
  ports:
  - port: 3306
    targetPort: 3306 # should match against the containerPort



